optical_flow_regularisation: 0.01
num_iter: 100
num_warp: 1
denoising_std: 0.5
denoising_indices:
  Followers_CTL: [0, 1, 2, 7]
  Followers_KO: [0, 1, 2, 3, 4, 5, 9]
  Leaders_CTL: [0, 1, 2, 3, 5, 6, 7, 13, 15]
  Leaders_KO: [0, 1, 2, 3, 4, 8, 11, 14, 25] # [1, 3, 4, 5, 9, 12, 21]
visuals: True
plot_threshold: 1.5
XY_resolution: 0.1625