optical_flow_regularisation: 0.01
num_iter: 100
num_warp: 1
denoising_indices:
  Population_1:
    0: 19
    1: 20
  Population_2:
    0: 20
    1: 14
visuals: True
plot_threshold: 1.5
XY_resolution: 0.1625