name: deformation_analysis
channels:
  - conda-forge
dependencies:
  # Core scientific stack
  - python=3.13.7
  - numpy=2.3.3
  - scipy=1.16.2
  - scikit-image=0.25.2
  - matplotlib=3.10.6
  - pandas=2.3.2
  - tqdm

  # Jupyter ecosystem
  - jupyterlab=4.4.7
  - ipykernel
  - notebook
  - widgetsnbextension

  # Image processing
  - tifffile=2025.9.20

  # Misc utilities
  - pip:
      - pydantic==2.11.9
      - openpyxl==3.1.5
      - nd2reader==3.3.1
      - matplotlib-scalebar==0.9.0
